scoring: gini # do wyboru: accuracy, f1, roc_auc, gini

models:
  decision_tree:
    type: sklearn.tree.DecisionTreeClassifier
    params:
      max_depth: 5
      random_state: 42

  random_forest:
    type: sklearn.ensemble.RandomForestClassifier
    params:
      n_estimators: 200
      max_depth: 10
      random_state: 42

  xgboost:
    type: xgboost.XGBClassifier
    params:
      n_estimators: 300
      learning_rate: 0.1
      max_depth: 4
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42

  lightgbm:
    type: lightgbm.LGBMClassifier
    params:
      n_estimators: 300
      learning_rate: 0.1
      max_depth: -1
      random_state: 42

  catboost:
    type: catboost.CatBoostClassifier
    params:
      iterations: 300
      learning_rate: 0.1
      depth: 6
      verbose: False
      random_seed: 42
